server:
  port: 8888
  servlet:
    context-path: /springcloud

spring:
  datasource:
        url: jdbc:mysql://www.hellofyy.top:3306/demo
        username: root
        password: fyy123
        driver-class-name: com.mysql.jdbc.Driver



mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: {com.springcloud.demo.entity,com.springcloud.demo.shiro.entity}
#RocketMQ

logging:
  level:
     com.springcloud.demo.shiro.dao : debug


